load("@bazel_tools//tools/build_defs/pkg:pkg.bzl", "pkg_tar")

filegroup(
    name = "all_files",
    srcs = [
        "404.html",
        "grow.html",
        "index.html",
        "js/grow.js",
        "js/index.js",
        "squirrels_go_away.html",
    ],
    visibility = ["//:__pkg__"],
)
